### ISSUE TITLE
Does not work with mocha's "require interface"

### ISSUE THREAD

**Issue by parasyte** [danielstjules/mocha.parallel#33]
See docs: https://mochajs.org/#require

Adding a reference to the `it` function completely breaks the parallel functionality:

```javascript
var parallel = require('mocha.parallel');
var Promise  = require('bluebird');
var it = require('mocha').it;

parallel('delays', function() {
  it('test1', function(done) {
    setTimeout(done, 500);
  });

  it('test2', function(done) {
    setTimeout(done, 500);
  });

  it('test3', function() {
    return Promise.delay(500);
  });
});
```

I understand that `mocha.parallel` works by patching the `it` reference. As far as I can tell, there's no way to get access to the parallel implementation of `it`, since the function is buried deep in a closure and otherwise not exposed by the module: https://github.com/danielstjules/mocha.parallel/blob/0b9109df70b5ce944ddcd37c60279d40c8ef2ea9/lib/parallel.js#L215-L232

Using `global.it = ...` does work, of course, but that's no better than Mocha's pollution of the global namespace.

**Comment by danielstjules** [comment]
FYI, even when using the require "interface", mocha is still polluting the global namespace with `it` & co.

But I can def update mocha.parallel to expose it/xit:
``` javascript
var parallel = require('mocha.parallel');
var it = parallel.it;
```

**Comment by parasyte** [comment]
Yep, I'm aware that Mocha pollutes regardless. This API just looks nicer, and I don't have to specify to eslint that it should expect the "mocha" environment.

**Comment by danielstjules** [comment]
Looked into it a bit this evening. Looks like this a solution wouldn't be as clean as I anticipated, since adding specs involves some state local to a particular "parallel" block (the list of specs in that suite). This can be seen in how `createSpec` modifies the `specs` array. So we'd need to keep track of the current parallel suite to accommodate that. 

Unfortunately I'm busy with other projects at the moment, but would welcome a PR!
